create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  role text not null default 'roommate',
  created_at timestamp with time zone default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'General',
  priority text not null default 'Medium',
  assigned_to text,
  completed boolean not null default false,
  status text not null default 'Planned',
  created_at timestamp with time zone default now()
);

create table if not exists public.flat_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default 'Roommate',
  created_at timestamp with time zone default now()
);

create table if not exists public.rent_entries (
  id bigint generated by default as identity primary key,
  month_label text not null,
  total_rent numeric not null default 0,
  total_expenses numeric not null default 0,
  member_amounts jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists public.monthly_expenses (
  id bigint generated by default as identity primary key,
  title text not null,
  amount numeric not null default 0,
  category text not null default 'Other',
  month_label text not null,
  created_at timestamp with time zone default now()
);

alter table public.users enable row level security;
alter table public.tasks enable row level security;
alter table public.flat_members enable row level security;
alter table public.rent_entries enable row level security;
alter table public.monthly_expenses enable row level security;

drop policy if exists "Allow public read access to users" on public.users;
create policy "Allow public read access to users"
  on public.users
  for select
  using (true);

drop policy if exists "Allow public insert access to users" on public.users;
create policy "Allow public insert access to users"
  on public.users
  for insert
  with check (true);

drop policy if exists "Allow public update access to users" on public.users;
create policy "Allow public update access to users"
  on public.users
  for update
  using (true)
  with check (true);

drop policy if exists "Allow public read access to tasks" on public.tasks;
create policy "Allow public read access to tasks"
  on public.tasks
  for select
  using (true);

drop policy if exists "Allow public insert access to tasks" on public.tasks;
create policy "Allow public insert access to tasks"
  on public.tasks
  for insert
  with check (true);

drop policy if exists "Allow public update access to tasks" on public.tasks;
create policy "Allow public update access to tasks"
  on public.tasks
  for update
  using (true)
  with check (true);

drop policy if exists "Allow public read access to flat_members" on public.flat_members;
create policy "Allow public read access to flat_members"
  on public.flat_members
  for select
  using (true);

drop policy if exists "Allow public insert access to flat_members" on public.flat_members;
create policy "Allow public insert access to flat_members"
  on public.flat_members
  for insert
  with check (true);

drop policy if exists "Allow public update access to flat_members" on public.flat_members;
create policy "Allow public update access to flat_members"
  on public.flat_members
  for update
  using (true)
  with check (true);

drop policy if exists "Allow public read access to rent_entries" on public.rent_entries;
create policy "Allow public read access to rent_entries"
  on public.rent_entries
  for select
  using (true);

drop policy if exists "Allow public insert access to rent_entries" on public.rent_entries;
create policy "Allow public insert access to rent_entries"
  on public.rent_entries
  for insert
  with check (true);

drop policy if exists "Allow public update access to rent_entries" on public.rent_entries;
create policy "Allow public update access to rent_entries"
  on public.rent_entries
  for update
  using (true)
  with check (true);

drop policy if exists "Allow public read access to monthly_expenses" on public.monthly_expenses;
create policy "Allow public read access to monthly_expenses"
  on public.monthly_expenses
  for select
  using (true);

drop policy if exists "Allow public insert access to monthly_expenses" on public.monthly_expenses;
create policy "Allow public insert access to monthly_expenses"
  on public.monthly_expenses
  for insert
  with check (true);

drop policy if exists "Allow public update access to monthly_expenses" on public.monthly_expenses;
create policy "Allow public update access to monthly_expenses"
  on public.monthly_expenses
  for update
  using (true)
  with check (true);
